
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5173"
    volumes:
      - .:/app
      - node_modules_dev:/app/node_modules
    container_name: help_frontend_dev

volumes:
  node_modules_dev: